---

- name: Add PostgreSQL repo
  yum: name=http://yum.postgresql.org/{{postgres_version}}/redhat/rhel-6-x86_64/pgdg-redhat{{postgres_version2}}-{{postgres_version}}-1.noarch.rpm update_cache=yes state=present

- name: Install PostgreSQL
  yum: name={{ item }} state=latest
  with_items:
    - postgresql{{postgres_version2}}
    - postgresql{{postgres_version2}}-server
    - postgresql{{postgres_version2}}-contrib
    - python-psycopg2

- name: Setup PostgreSQL
  command: /usr/pgsql-{{postgres_version}}/bin/postgresql{{postgres_version2}}-setup initdb creates=/var/lib/pgsql/{{postgres_version}}/initdb.log

- name: Ensure PostgreSQL is running
  service: name=postgresql-{{postgres_version}} state=started enabled=yes

- name: Copy postgresql.conf
  copy: src=postgresql.conf dest=/var/lib/pgsql/{{postgres_version}}/data owner=root group=root mode=0644
  notify:
    - postgres-restart

- name: Copy pg_hba.conf
  copy: src=pg_hba.conf dest=/var/lib/pgsql/{{postgres_version}}/data owner=root group=root mode=0644
  notify:
    - postgres-restart

- name: Set password for postgres role
  postgresql_user:
    name: postgres
    password: "{{ lookup('password', '~/.ansible/lookups/' + project_name + '/' + server_hostname + '/pgpw-postgres length=32') }}"
  sudo: yes
  sudo_user: "{{postgres_admin_user}}"
