---
# This playbook contains common plays that will be run on all nodes.

- name: update apt cache
  apt: update_cache=yes cache_valid_time=3600

- name: Install NTP
  apt: name=ntp state=present

- name: Install useful packages
  apt: name={{ item }} state=present
  with_items:
    - python-apt
    - python-pip
    - python-software-properties
    - curl
    - htop
    - sysstat
    - tree
    - vim

- name: Ensure bash is up-to-date
  apt: name=bash state=latest

- name: Install PycURL -- cURL library module for Python
  pip: name=pycurl

