---
# This playbook contains common plays that will be run on all nodes.

- name: Copy EPEL's GPG key
  copy: src=RPM-GPG-KEY-EPEL-7 dest=/etc/pki/rpm-gpg owner=root group=root mode=0644

- name: Copy EPEL's repo file
  copy: src=epel.repo dest=/etc/yum.repos.d/ owner=root group=root mode=0644

- name: Install epel-release package
  yum: name=epel-release update_cache=yes state=installed enablerepo=epel

- name: Install NTP
  yum: name=ntp state=present

- name: Install pip
  yum: name=python-pip state=present

- name: Install curl
  yum: name=curl state=present

- name: Install PycURL -- cURL library module for Python
  pip: name=pycurl

- name: Install yum-utils
  yum: name=yum-utils state=present
