---
# This playbook contains common plays that will be run on all nodes.

- name: Install the EPEL repo
  yum: name=epel-release state=latest

- name: Install NTP
  yum: name=ntp state=present

- name: Install pip
  yum: name=python-pip state=present update_cache=yes

- name: Install curl
  yum: name=curl state=present

- name: Install PycURL -- cURL library module for Python
  pip: name=pycurl

