---

- name: Add nginx deb repository
  apt_repository: repo='deb http://nginx.org/packages/ubuntu/ trusty nginx' state=present

- name: Add nginx deb-src repository
  apt_repository: repo='deb-src http://nginx.org/packages/ubuntu/ trusty nginx' state=present

- name: Add nginx's public key to trusted key list
  apt_key: url=http://nginx.org/keys/nginx_signing.key state=present

- name: Install nginx
  apt: name=nginx update_cache=yes state=present

- name: write nginx.conf
  action: template src=nginx.conf.j2 dest=/etc/nginx/nginx.conf
  notify:
    - nginx-restart

- name: delete default vhost
  action: file path=/etc/nginx/conf.d/default.conf state=absent
  notify:
    - nginx-restart

- name: sites-enabled dir
  action: file dest=/etc/nginx/sites-enabled mode=755 owner=root group=root state=directory

- name: write vhost
  action: template src=vhost.j2 dest=/etc/nginx/sites-enabled/{{ server_hostname }}
  notify:
    - nginx-restart