---

- name: Install PHP
  yum: name={{ item }} state=latest
  with_items:
    - php-common
    - php-fpm
    - php-gd
    - php-mcrypt
    - php-cli
- name: Write php.ini
  template: src=php.ini dest=/etc/php.ini
  notify:
    - php-fpm-restart

- name: Write php-fpm.conf
  template: src=php-fpm.conf dest=/etc/php-fpm.conf
  notify:
    - php-fpm-restart

- name: Write php fpm pool config
  template: src=php-fpm.d/www.conf dest=/etc/php-fpm.d/www.conf
  notify:
    - php-fpm-restart

- name: Start PHP-FPM
  service: name=php-fpm state=started enabled=yes

- name: Install PostgreSQL support
  yum: name=php-pgsql state=latest
  when: postgres_user_privileges|length > 0
  notify:
    - php-fpm-restart

- name: Install git
  yum: name=git state=latest

- name: Install Composer
  shell:
    curl -sS https://getcomposer.org/installer | php && /bin/mv -f /home/vagrant/composer.phar /usr/local/bin/composer
    creates=/usr/local/bin/composer

- name: Add {{ bin_dir }} to PATH
  lineinfile: >
   dest=/etc/environment
   state=present
   backrefs=yes
   regexp='PATH=(["]*)((?!.*?{{ bin_dir }}).*?)(["]*)$'
   line="PATH=\1\2:{{ bin_dir }}\3"
  when: bin_dir is defined

# install optional php extensions
# install xdebug
