---

- name: Install OpenJDK Java runtime
  yum: name=java-1.7.0-openjdk update_cache=yes state=present

- name: Download and install the Public Signing Key
  rpm_key: state=present key=https://packages.elastic.co/GPG-KEY-elasticsearch

- name: Add elasticsearch rpm repository
  template: src=yum.repos.d/elasticsearch.repo dest=/etc/yum.repos.d/elasticsearch.repo

- name: Install elasticsearch
  yum: name=elasticsearch update_cache=yes state=present
  notify:
    - elasticsearch-start

- name: write elasticsearch.yml
  template: src=elasticsearch/elasticsearch.yml dest=/etc/elasticsearch/elasticsearch.yml
  notify:
    - elasticsearch-restart

- name: write logging.yml
  template: src=elasticsearch/logging.yml dest=/etc/elasticsearch/logging.yml
  notify:
    - elasticsearch-restart

- name: Ensure elasticsearch starts on boot up
  service: name=elasticsearch state=started enabled=yes
