---

- name: Write vhost
  template: src=default.conf dest=/etc/nginx/sites-enabled/{{ server_hostname }}
  notify:
    - nginx-restart

- name: Write vhost
  template: src=sf2_env_cars.sh dest=/etc/profile.d/sf2_env_cars.sh

- name: Install ACL utilities
  yum: name={{ item }} state=present
  with_items:
  - acl

- name: Mount root filesystem with acl support
  mount: name=/ src=/dev/sda1 fstype=ext4 opts=errors=remount-ro,acl state=present

- name: Create cache directory
  sudo: Yes
  command:
    mkdir -p {{ sf2_cache_dir }}
    creates={{ sf2_cache_dir }}

- name: Create log directory
  sudo: Yes
  command:
    mkdir -p {{ sf2_log_dir }}
    creates={{ sf2_log_dir }}

- name: Update ACLs for cache/log directories
  sudo: Yes
  command: setfacl -R -m u:nginx:rwX -m u:vagrant:rwX {{ sf2_cache_dir }} {{ sf2_log_dir }}

- name: Update default ACLs for cache/log directories
  sudo: Yes
  command: setfacl -dR -m u:nginx:rwX -m u:vagrant:rwX {{ sf2_cache_dir }} {{ sf2_log_dir }}

- name: Clear the cache
  command:
    ./app/console cache:clear -e prod --no-debug
    chdir={{ project_root }}
    creates={{ project_root }}/app/cache/prod/appProdProjectContainer.php
  environment:
    SYMFONY__DATABASE__DRIVER: "{{ database_driver }}"
    SYMFONY__DATABASE__HOST: "{{ database_host }}"
    SYMFONY__DATABASE__PORT: "{{ database_port }}"
    SYMFONY__DATABASE__NAME: "{{ postgres_dbs[0].name }}"
    SYMFONY__DATABASE__USER: "{{ postgres_users[0].username }}"
    SYMFONY__DATABASE__PASSWORD: "{{ postgres_users[0].password }}"
    SYMFONY__SF2_SECRET: "{{ sf2_secret }}"
    

- name: Dump all assets to the filesystem
  command:
    ./app/console assetic:dump -e prod --no-debug
    chdir={{ project_root }}

- name: Install bundles' web assets under the public web directory
  command:
    ./app/console assets:install -e prod --no-debug
    chdir={{ project_root }}
