---

- name: Install composer dependencies
  yum: name={{item}} state=present
  with_items:
    - git
    - php-pecl-zip
  notify:
    - php-fpm-restart

- name: Install Composer
  get_url: url=https://getcomposer.org/composer.phar dest=/usr/local/bin/composer

- name: Add composer bin directory to PATH
  lineinfile: >
   dest=/etc/environment
   state=present
   backrefs=yes
   regexp='PATH=(["]*)((?!.*?{{ bin_dir }}).*?)(["]*)$'
   line="PATH=\1\2:{{ bin_dir }}\3"
  when: bin_dir is defined