---

- name: Install the EPEL repository configuration package
  yum: name=https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm state=present

- name: Install the Remi repository configuration package
  yum: name=http://rpms.remirepo.net/enterprise/remi-release-7.rpm state=present

- name: Enable the repository
  command: yum-config-manager --enable remi-{{php_version}}

- name: Install PHP
  yum: name={{item}} state=latest update_cache=yes
  with_items:
    - php-common
    - php-fpm
    - php-gd
    - php-mcrypt
    - php-cli
    - php-opcache
    - php-mbstring
    - php-xml

- name: Configure PHP
  template: src=php.ini dest=/etc/php.ini
  notify:
    - php-fpm-restart

- name: Configure PHP-FPM
  template: src=php-fpm.conf dest=/etc/php-fpm.conf
  notify:
    - php-fpm-restart

- file: path=/etc/php-fpm.d state=directory mode=0755

- name: Configure PHP-FPM pool
  template: src=php-fpm.d/www.conf dest=/etc/php-fpm.d/www.conf
  notify:
    - php-fpm-restart

- name: Start PHP-FPM
  service: name=php-fpm state=started enabled=yes

- name: Install PostgreSQL support
  yum: name={{item}} state=present
  when: postgres_user_privileges|length > 0
  with_items:
    - php-pgsql
    - php-pdo
  notify:
    - php-fpm-restart

- name: Install xdebug
  yum: name=php-pecl-xdebug state={{ (install_xdebug == 1) | ternary('latest','absent') }}
  notify:
    - php-fpm-restart
