---

- name: postgres-start
  service: name=postgresql-{{postgres_version}} start=started

- name: postgres-stop
  service: name=postgresql-{{postgres_version}} start=stopped

- name: postgres-restart
  service: name=postgresql-{{postgres_version}} state=restarted

- name: postgres-reload
  service: name=postgresql-{{postgres_version}} state=reloaded